services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: Hardik
      POSTGRES_PASSWORD: Hard123@c
      PGDATA: /data/postgres
    volumes:
      - db:/datapostgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: